"use client";

import MySessionProvider from "@/components/providers/MySessionProvider";
import PageTransition from "@/components/transitions/PageTransition";
import "./globals.scss";
import HeaderMenu from "@/components/headerMenu/HeaderMenu";
// import { AnimatePresence, motion } from "framer-motion";
// import { usePathname } from "next/navigation";
// import { useEffect, useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const [mounted, setMounted] = useState(false);
  // useEffect(() => setMounted(true), []);

  // const pathname = usePathname();

  // const variants = {
  //   initial: { x: 300, opacity: 0 },
  //   animate: { x: 0, opacity: 1 },
  //   exit: { x: -300, opacity: 0 },
  // };

  // if (!mounted) return null;

  return (
    <html lang="en">
      <body>
        <MySessionProvider>
          <HeaderMenu />
          <PageTransition>{children}</PageTransition>
        </MySessionProvider>
      </body>
    </html>
  );
}
